config/routes.rb
Ticketee::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :projects do
        resources :tickets
      end
    end
  end
 namespace :api do
   namespace :v2 do
     resources :projects do
       resources :tickets
     end
   end
 end
  

  devise_for :users, controllers: { registrations: "registrations" }
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end
  get '/awaiting_confirmation',
      to: "users#confirmation",
      as: 'confirm_user'

  root to: "projects#index"
  
  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
      
      member do
        post :watch
      end
    end 
  end
  
  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end
  
  namespace :admin do
    root to: "base#index"
    resources :users do
      resources :permissions
    end
    resources :states do
      member do
        get :make_default
      end
    end
  end
  
  
  
  put '/admin/users/:user_id/permissions', to: 'admin/permissions#update', as: :update_user_permissions
  
  resources :files 
    
  

end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :background, :color, :name, :default
  def to_s
    name
  end
  
  def default!
    current_default_state = State.find_by_default(true)
    
    self.default = true
    self.save!
    
    if current_default_state
      current_default_state.default = false
      current_default_state.save!
    end
  end
  
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < Admin::BaseController
  def index
    @states = State.all
  end
  
  def new
    @state = State.new
  end
  
  def create 
    @state = State.new(params[:state])
    if @state.save
      flash[:notice] = "State has been created."
      redirect_to admin_states_path
    else
      flash[:alert] = "State has not been created."
      redirect_to action: 'new'
    end
  end
  
  def make_default
    @state = State.find(params[:id])
    @state.default!
    
    
    
    
    flash[:notice] = "#{@state.name} is now the default state."
    redirect_to admin_states_path
    
  end
  
end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= form_for [:admin, @state] do |f| %>
<p>
	<%= f.label :name %>
	<%= f.text_field :name %>
</p>

<%= f.submit %>
<% end %>

app/views/admin/states/index.html.erb
<%= link_to "New State", new_admin_state_path %>
<ul id="states">
	<% @states.each do |state| %>
	<li id='state_<%= state.id %>'>
    <%= state.name %>
    <% if state.default? %>
      (Default)
    <% else %>
      <%= link_to "Make Default", make_default_admin_state_path(state) %>
    <% end %>
  </li>
	<% end %>
</ul>

app/views/admin/states/make_default.html.erb
<p><%= debug @state %></p>
<% @state.save! %>

app/views/admin/states/new.html.erb
<h1>New States</h1>
<%= render 'form' %>